ERROR - 2021-10-23 07:50:47 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2021-10-23 07:50:47 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 C:\xampp\htdocs\secret_shopp\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\secret_shopp\system\Database\BaseBuilder.php(1429): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\secret_shopp\system\Model.php(145): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\secret_shopp\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#4 C:\xampp\htdocs\secret_shopp\app\Controllers\Gerencia.php(48): CodeIgniter\BaseModel->find()
#5 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(824): App\Controllers\Gerencia->view_get()
#6 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gerencia))
#7 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\secret_shopp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2021-10-23 07:53:25 --> Error connecting to the database: Unknown database 'secret_shopp'
CRITICAL - 2021-10-23 07:53:25 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'secret_shopp'
#0 C:\xampp\htdocs\secret_shopp\system\Database\BaseConnection.php(570): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\secret_shopp\system\Database\BaseBuilder.php(1429): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\secret_shopp\system\Model.php(145): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\secret_shopp\system\BaseModel.php(523): CodeIgniter\Model->doFind(false, NULL)
#4 C:\xampp\htdocs\secret_shopp\app\Controllers\Gerencia.php(48): CodeIgniter\BaseModel->find()
#5 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(824): App\Controllers\Gerencia->view_get()
#6 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gerencia))
#7 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\secret_shopp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-10-23 07:55:35 --> Undefined property: App\Controllers\Gerencia::$load
#0 C:\xampp\htdocs\secret_shopp\app\Controllers\Gerencia.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(824): App\Controllers\Gerencia->view_get()
#2 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gerencia))
#3 C:\xampp\htdocs\secret_shopp\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\secret_shopp\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-10-23 08:12:11 --> Undefined property: App\Controllers\Gerencia::$load
#0 C:\xampp\htdocs\loja_dota\app\Controllers\Gerencia.php(52): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined prope...', 'C:\\xampp\\htdocs...', 52)
#1 C:\xampp\htdocs\loja_dota\system\CodeIgniter.php(824): App\Controllers\Gerencia->view_get()
#2 C:\xampp\htdocs\loja_dota\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Gerencia))
#3 C:\xampp\htdocs\loja_dota\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\loja_dota\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-10-23 08:29:39 --> include(C:\xampp\htdocs\loja_dota\system\Debug/Toolbar/Views/toolbarloader.js.php): Failed to open stream: No such file or directory
#0 C:\xampp\htdocs\loja_dota\system\Debug\Toolbar.php(438): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(C:\\xamp...', 'C:\\xampp\\htdocs...', 438)
#1 C:\xampp\htdocs\loja_dota\system\Debug\Toolbar.php(438): include()
#2 C:\xampp\htdocs\loja_dota\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\loja_dota\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\loja_dota\system\CodeIgniter.php(300): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\loja_dota\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-10-23 08:32:46 --> include(C:\xampp\htdocs\loja_dota\system\Debug/Toolbar/Views/toolbarloader.js.php): Failed to open stream: No such file or directory
#0 C:\xampp\htdocs\loja_dota\system\Debug\Toolbar.php(438): CodeIgniter\Debug\Exceptions->errorHandler(2, 'include(C:\\xamp...', 'C:\\xampp\\htdocs...', 438)
#1 C:\xampp\htdocs\loja_dota\system\Debug\Toolbar.php(438): include()
#2 C:\xampp\htdocs\loja_dota\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 C:\xampp\htdocs\loja_dota\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 C:\xampp\htdocs\loja_dota\system\CodeIgniter.php(300): CodeIgniter\Events\Events::trigger('pre_system')
#5 C:\xampp\htdocs\loja_dota\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
